version: "3.7"

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    working_dir: /usr/src/web/
    volumes:
      - ./web:/usr/src/web
      - static_volume:/usr/src/web/static
      - media_volume:/usr/src/web/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - front
      - back
  db:
    image: postgres:12.0
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - back
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/web/static
      - media_volume:/usr/src/web/media
    ports:
      - 1337:80
    depends_on:
      - django
    networks:
      - front

volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  front:
    external: false
  back:
    external: false
